// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Função para pegar variáveis de ambiente na web
  static String _getEnvVar(String key, [String defaultValue = '']) {
    if (kIsWeb) {
      // Na web, use String.fromEnvironment
      return String.fromEnvironment(key, defaultValue: defaultValue);
    } else {
      // Em outras plataformas, use dotenv
      return dotenv.env[key] ?? defaultValue;
    }
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _getEnvVar('FIREBASE_WEB_API_KEY'),
    appId: _getEnvVar('FIREBASE_WEB_APP_ID'),
    messagingSenderId: _getEnvVar('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _getEnvVar('FIREBASE_PROJECT_ID'),
    authDomain: '${_getEnvVar('FIREBASE_PROJECT_ID')}.firebaseapp.com',
    storageBucket: '${_getEnvVar('FIREBASE_PROJECT_ID')}.firebasestorage.app',
    measurementId: _getEnvVar('FIREBASE_WEB_MEASUREMENT_ID'),
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _getEnvVar('FIREBASE_ANDROID_API_KEY'),
    appId: _getEnvVar('FIREBASE_ANDROID_APP_ID'),
    messagingSenderId: _getEnvVar('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _getEnvVar('FIREBASE_PROJECT_ID'),
    storageBucket: '${_getEnvVar('FIREBASE_PROJECT_ID')}.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _getEnvVar('FIREBASE_IOS_API_KEY'),
    appId: _getEnvVar('FIREBASE_IOS_APP_ID'),
    messagingSenderId: _getEnvVar('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _getEnvVar('FIREBASE_PROJECT_ID'),
    storageBucket: '${_getEnvVar('FIREBASE_PROJECT_ID')}.firebasestorage.app',
    iosBundleId: _getEnvVar('FIREBASE_IOS_BUNDLE_ID'),
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _getEnvVar('FIREBASE_MACOS_API_KEY'),
    appId: _getEnvVar('FIREBASE_MACOS_APP_ID'),
    messagingSenderId: _getEnvVar('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _getEnvVar('FIREBASE_PROJECT_ID'),
    storageBucket: '${_getEnvVar('FIREBASE_PROJECT_ID')}.firebasestorage.app',
    iosBundleId: _getEnvVar('FIREBASE_MACOS_BUNDLE_ID'),
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: _getEnvVar('FIREBASE_WINDOWS_API_KEY'),
    appId: _getEnvVar('FIREBASE_WINDOWS_APP_ID'),
    messagingSenderId: _getEnvVar('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _getEnvVar('FIREBASE_PROJECT_ID'),
    storageBucket: '${_getEnvVar('FIREBASE_PROJECT_ID')}.firebasestorage.app',
  );
}
